
server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres-database:5432/auth_service_db
    username: postgres
    password: Pass@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

jwt:
  secret: myVeryStrongSecretKeyForJwtAuthentication123456789
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
