server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:postgresql://postgres-database:5432/payment_service_db
    username: postgres
    password: Pass@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587

    username: khandekarom5505@gmail.com
    password: xprj kipa lzkn yumo

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,metrics

  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:

      orderServiceBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

jwt:
  secret: myVeryStrongSecretKeyForJwtAuthentication123456789

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
